// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVgDVI7VPSEvQaGl1rfqe_K3ECVg6CNs',
    appId: '1:1063166335100:web:d691aa0101a87fa28511f9',
    messagingSenderId: '1063166335100',
    projectId: 'scp-asistente',
    authDomain: 'scp-asistente.firebaseapp.com',
    storageBucket: 'scp-asistente.firebasestorage.app',
    measurementId: 'G-QC8C635C0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsH5CfJcNtUD4mN1qoCUEBfbHrH7g3i38',
    appId: '1:1063166335100:android:ab19e1e7644a1f2a8511f9',
    messagingSenderId: '1063166335100',
    projectId: 'scp-asistente',
    storageBucket: 'scp-asistente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFmMGy0cQnuhchrSEanc9a--AM2hRkYk',
    appId: '1:1063166335100:ios:8c9efd19b85297258511f9',
    messagingSenderId: '1063166335100',
    projectId: 'scp-asistente',
    storageBucket: 'scp-asistente.firebasestorage.app',
    iosBundleId: 'com.example.frontendSpc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFmMGy0cQnuhchrSEanc9a--AM2hRkYk',
    appId: '1:1063166335100:ios:8c9efd19b85297258511f9',
    messagingSenderId: '1063166335100',
    projectId: 'scp-asistente',
    storageBucket: 'scp-asistente.firebasestorage.app',
    iosBundleId: 'com.example.frontendSpc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVgDVI7VPSEvQaGl1rfqe_K3ECVg6CNs',
    appId: '1:1063166335100:web:508ae88255d9f8d78511f9',
    messagingSenderId: '1063166335100',
    projectId: 'scp-asistente',
    authDomain: 'scp-asistente.firebaseapp.com',
    storageBucket: 'scp-asistente.firebasestorage.app',
    measurementId: 'G-GQ9Y583H7H',
  );
}
